name: weifangbus
description: 潍坊公交
version: 2.0.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.1.10
  device_info_plus: ^10.1.0
  connectivity_plus: ^6.0.2
  dio: ^5.1.1
  crypto: ^3.0.2
  intl: 0.18.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  easy_refresh: ^3.3.1+1
  easy_refresh_bubbles: ^1.0.0
  provider: ^6.0.5
  auto_size_text: ^3.0.0
  flutter_widget_from_html_core: ^0.14.9
  photo_view: ^0.15.0
  shared_preferences: ^2.1.0
  package_info_plus: ^7.0.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/guide/
    - assets/images/home/
  fonts:
    - family: myIcon
      fonts:
        - asset: fonts/iconfont.ttf
  # 国际化
  generate: true
